version: "3"
services:
  strapiDB:
    container_name: centif-strapiDB
    env_file: ./backend/.env
    image: mysql:5.7
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/mysql
    ports:
      - "3356:3306"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
