version: "3"
services:
  strapiDB:
    container_name: centif-strapiDB
    image: mysql:5.7
    environment:
      MYSQL_USER: centif
      MYSQL_ROOT_PASSWORD: centif
      MYSQL_PASSWORD: centif
      MYSQL_DATABASE: centif
    volumes:
      - strapi-data:/var/lib/mysql
    ports:
      - "3356:3306"
    networks:
      - strapi

  pma:
    container_name: centif-pma
    image: phpmyadmin:5.1
    networks:
      - strapi
    environment:
      PMA_HOST: strapiDB
      PMA_USER: root
      PMA_PASSWORD: centif
    depends_on:
      - strapiDB
    ports:
      - 8899:80

  backend:
    container_name: centif-backend
    build:
      context: .
    depends_on:
      - strapiDB
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "1337:1337"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
